language: scala
jdk:
- openjdk8
sudo: false
script:
- sbt test
env:
  secure: Tb3ZjIT2Na52bnW6Pq82mVNKXCLOoG/ao/gh8dS3IucshYdr1gVRb7u2IX06hxPhl6C541XeJ3/u+8jBcpcyt/FaoGavJHND/sS/yKM/NRabVQDbQgv6MAojTlRsH/xCIfzR4Oju7NTjAInEUTSjg3oAw+pWiUEgvu5BhHBbcN8f4D2C962wDQ6rZ7x5OuI6KvAgjRLSHRvDr+HWzv0a9Ua5duD4iib4mOVoZHOQh/1qqRuwCArDZBC5r7Cl2v6M0tq5T2r5uYF5f9ljGBJVT5Sqrykg3M7pRoYTR3YNd3x6tX5Hr1ZGLWAA+7pcM0LqoZekOJliMJbof4yHF06GGgo4QIGzPiW8EULj/ZCgpuVqlFkm5E65xjp7DzCgs2SjUp58/d/5wVl/YOLy2XWovd8TsQeQoOgE/Iiz5wlX+g8I/h36b0hMgYq98LkhvNxEVXGl1Feeenm524xNZTEqlCLqetl1uIklhp+zbmfGDVTMClD0n6Olc0e+Ds4U0HLcnZpFPCQCkQtjm2bJqQp7E1FieNeA/PrQEiOsz8MfQQY3Bm++lrbFKaYrBtgEYXfGtf+n17pl1M+8pNpiVEvHfB+RZtCn9xBtrYJGOfuNqdztS1d5us/ey4f/uU7Pgz/4BMZXBf6zAQvLGBQTAh3euYCVr6f8mlZKNMsTs0CKC5c=
